### ISSUE TITLE
New Relic script causes diffs on every page

### ISSUE THREAD

**Issue by chosak** [cfpb/crawl-cfgov#6]
We're seeing diffs on almost every page due to a New Relic JavaScript snippet which is included in the page head. For example, on [this commit](https://github.com/cfpb/crawl-cfgov/commit/7417690cf755af2af7e8b08299b0a1859b75d09c), the page at www.consumerfinance.gov/1071-rule/ changes its JS snippet from

`..."queueTime":1,"applicationTime":350...`

to

`..."queueTime":2,"applicationTime":1812...`

This can be more easily seen with a command like:

```sh
$ git diff --word-diff=color --word-diff-regex=. HEAD~1 -- www.consumerfinance.gov/1071-rule/index.html
```

This script gets added to our pages by [the New Relic Python agent](https://docs.newrelic.com/docs/agents/python-agent). We use the ["Enable via APM"](https://docs.newrelic.com/docs/browser/new-relic-browser/installation/install-browser-monitoring-agent#select-apm-app) method of inserting the JS snippet.

It appears based on these diffs that this snippet can vary, which would result in meaningless changes like these. To reproduce, visit a cf.gov page that isn't behind Akamai, for example [any Ask CFPB page](https://www.consumerfinance.gov/ask-cfpb/what-effect-will-shopping-for-an-auto-loan-have-on-my-credit-en-763/). View source, and look at the New Relic JS snippet in the page `<head>` (it'll be the last `<script>` tag). Reload the page a few times and notice that the script content changes.

One option to fix this would be to modify our diff somehow to ignore this line.

Alternatively, New Relic also supports [manually adding the JS snippet](https://docs.newrelic.com/docs/browser/new-relic-browser/installation/install-browser-monitoring-agent#copy-paste-app). This wouldn't change and thus would avoid this problem completely.

**Comment by schbetsy** [comment]
A related but broader question: The user stories for this archive seem mostly oriented toward detecting content changes to the site, i.e. changes that are not reflected in consumerfinance.gov source control. In that case, do we think *any* `<script>` tags would be useful in the archive? Script tags seem to be mostly minimized JS libraries, which will probably cause other meaningless diffs in addition to the New Relic ones.

I'd be fine with manually adding the New Relic JS snippet to prevent meaningless diffs in that particular line. But I'd also be interested in using some code to strip out `<script>` tags entirely (if you think this sounds reasonable). What do you think?

*(Aside)* I nearly suggested only including the `<body>` tag and discarding `<head>` entirely, but I realized that some things contained in `<head>`, are potentially useful to have in the archive, such as page title, meta description, etc. Do you agree with that?

**Comment by chosak** [comment]
@schbetsy great questions. I do agree that `<head>` contains some content that we'd want to track.

I've been thinking about this problem along two different but related axes: first, what content do we want to store in this repository, and, second, how do we want diffs and their related commit messages to work?

First, in terms of content, we could store:

- the full HTML of each page on the site
- the HTML of each page, but with certain elements removed (e.g. stripping `<script>`)
- only the text content, by stripping `<script>` and all of the HTML tags (e.g. using something like Django's [`strip_tags`](https://docs.djangoproject.com/en/3.1/ref/utils/#django.utils.html.strip_tags))

In any of these cases, we might additionally want to do some kind of processing to generate a smarter diff and/or commit message, that summarizes and ignores any irrelevant changes. One nice example of this is Simon Willison's work on [a commit log for San Francisco's trees](https://simonwillison.net/2019/Mar/13/tree-history/) (more generally, his work on [git scraping](https://simonwillison.net/2020/Oct/9/git-scraping/) is a big inspiration for this project). For his tree repository he wrote a [custom diff tool](https://github.com/simonw/csv-diff) to generate smarter diffs to a large CSV that then get stored as the commit message. Looking at [any individual commit](https://github.com/simonw/sf-tree-history/commit/e0aaaebd2fea20f24547b63557f4eb88a9d25f26) in GitHub, the file differences aren't really useable, but the commit message gives a nice summary. Maybe we could do something like that. 

A downside of storing raw HTML with potentially many diffs is that when browsing in GitHub, the commit view isn't particularly useable, especially if the HTML structure changes significantly. But maybe that's okay, if the commit messages give you a more easily readable list of changes. It'd be pretty neat to have a commit message like: "39 pages modified: A, B, C. 3 new pages published: X, Y, Z", where the pages link to the website. To get even more advanced, maybe the commit message could indicate which pages had text modifications and which only changed in their tags.

(In theory for local development we could set up a smarter diff using [.gitattributes](https://git-scm.com/docs/gitattributes#_generating_diff_text), although this feels like it'd be a bit too magical. GitHub [doesn't seem to support](https://stackoverflow.com/q/24212291) custom diff views beyond just excluding files.)

To me the advantage of storing the raw HTML is that we can always go back later and run a different diff algorithm to look for specific changes, whereas storing a reduced version eliminates that possibility. Having [less useful diffs on GitHub](https://github.com/cfpb/crawl-cfgov/commit/4582b20fbe31d5c99b1f5f8ac7838cac733bb06b) feels bad, but maybe outweighed by those advantages. What do you think?

More generally, part of the reason the diffs are so unreadable right now is that we do have these issues that cause spurious changes every time the page is loaded (see also #7). Both of these would be nice to fix for reasons beyond this archiving project: for example, I'm curious (and a little afraid) of how these constant diffs affect Akamai's ability to effectively cache the site pages...

**Comment by schbetsy** [comment]
> To me the advantage of storing the raw HTML is that we can always go back later and run a different diff algorithm to look for specific changes, whereas storing a reduced version eliminates that possibility.

I don't understand this. Do you mean that if, for example, we used a python script to exclude `<script>` tags, it wouldn't do so consistently enough to make the diffs meaningful?

**Comment by chosak** [comment]
> Do you mean that if, for example, we used a python script to exclude <script> tags, it wouldn't do so consistently enough to make the diffs meaningful?

Let's say we write a script that strips out `<script>` tags but then later have a need to determine when a `<script>`  was changed or added. We wouldn't be able to do that if we store the stripped version.

**Comment by schbetsy** [comment]
> New Relic also supports manually adding the JS snippet. This wouldn't change and thus would avoid this problem completely.

Is anything stopping us from doing this?

**Comment by chosak** [comment]
> Is anything stopping us from doing this?

Technically no: we can make the code changes to do this, although it might require adding one or more new environment variables to store either the JS snippet or just the private NR variables that are part of it (see "Application settings" under a New Relic Browser configuration to see an example of what the snippet looks like).

Practically, there are some other considerations to whether we should move to the manual snippet.

First, we'd have to make sure that all HTML pages get the snippet added. This means adding it both to the Wagtail base page template but also to any other legacy HTML templates that are used for cf.gov pages.

Second, it appears that the method we use has some impact on how the performance numbers are recorded. I dug into the Python agent code a bit and it looks like the varying `queueTime` and `applicationTime` numbers are generated [here](https://github.com/newrelic/newrelic-python-agent/blob/930d55cf2caf64052285e954add7e854f326050b/newrelic/api/web_transaction.py#L539-L564). Without fully  understanding how the agent code works, these numbers appear to be some kind of measurement of how long the web request waited and then took to be completed. But these values aren't in the manually inserted snippet -- is that a problem? what does that mean?

I found [a New Relic forum post](https://discuss.newrelic.com/t/ajax-timing-definitions/35456) that touches on this. It mentions some metrics that "only show up on your graph if you have backend performance being monitored through APM". I believe "through APM" means our current method, the first one [on this page](https://docs.newrelic.com/docs/browser/new-relic-browser/installation/install-browser-monitoring-agent). Moving to a manual snippet would mean we'd lose the ability to break out application time, queue time, network time, and callback time for AJAX requests -- we'd only get total request time. I don't know how much/if we use these metrics much now but it would  be a shame to lose them.

Maybe this means we shouldn't pursue this manual snippet idea?

**Comment by schbetsy** [comment]
I'm working on adding a step to the crawl workflow that deletes everything inside any `<script>` tag. This should eliminate bulk from the crawl and prevent many of the meaningless diffs that are currently being committed.

@chosak I think I'd also like to delete any blank lines in the html at the same time. Do you foresee issues with that? I think it'll help prevent unhelpful whitespace diffs.

**Comment by chosak** [comment]
@schbetsy sounds great. :+1:

**Comment by schbetsy** [comment]
This issue appears to be solved, now that we remove `<script>` tags from crawl results. [Here's](https://github.com/cfpb/crawl-cfgov/commit/895be24b59d1cabdd2df278978354ee8a2486434) what the new diffs look like without those tags.
