### ISSUE TITLE
Pages with email signups report meaningless diffs

### ISSUE THREAD

**Issue by chosak** [cfpb/crawl-cfgov#7]
Pages that contain an [`EmailSignUp`](https://github.com/cfpb/consumerfinance.gov/blob/385d5fb0de45652806a0f527418736073a1f2ebe/cfgov/v1/atomic_elements/organisms.py#L166) organism will report a diff every day because they are given a random `id` each time they are rendered.

Consider for example [this blog post](http://www.consumerfinance.gov/about-us/blog/2019-college-credit-card-report/), which has an email signup in the sidebar. This element will have a unique `id` each time it is rendered (modulo any extra nightly caching by Akamai).

The relevant template code is [here](https://github.com/cfpb/consumerfinance.gov/blob/146a9af377e85617210cf2ba57d7bfac1a317361/cfgov/jinja2/v1/_includes/organisms/email-signup.html#L23-L44), with the random identifier generated by a [`get_unique_id`](https://github.com/cfpb/consumerfinance.gov/blob/146a9af377e85617210cf2ba57d7bfac1a317361/cfgov/v1/util/util.py#L26-L28) method.

There are apparently other blocks that [also use `get_unique_id`](https://github.com/cfpb/consumerfinance.gov/search?q=get_unique_id), so this probably affects pages without email signups as well.

A possible fix for this would be to deprecate `get_unique_id` in favor of the unique StreamField block ID that gets automatically generated by Wagtail. This unique ID functionality has been in Wagtail [since release 1.11](https://docs.wagtail.io/en/stable/releases/1.11.html#other-features), and I believe `get_unique_id` was created when we were on an older version.

**Comment by schbetsy** [comment]
I opened [this PR](https://github.com/cfpb/consumerfinance.gov/pull/6106) on consumerfinance.gov to update the behavior of the email sign-up organism. This should make the ids consistent between page loads, so they should not show up as diffs in the archive.

After this PR, there will still be a few blocks in cf.gov that use `get_unique_id` and show diffs, but the vast majority will be removed. We can tackle the remaining blocks after that.

**Comment by schbetsy** [comment]
The email signups are no longer showing diffs in the archive!
